apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: headlamp
    repo: https://headlamp-k8s.github.io/headlamp/
    releaseName: headlamp
    namespace: headlamp
    version: 0.18.0
    valuesFile: values.yaml

resources:
  - ing_headlamp.yaml
  - ns_headlamp.yaml
  - sealedsecret_oidc.yaml