nodeSelector:
  infra: "true"
tolerations:
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

config:
  baseURL: "https://k8s-dashboard.klopfi.net"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    octodns-kubernetes.rybni.co/hostname: k8s-dashboard.klopfi.net
  hosts:
  - host: k8s-dashboard.klopfi.net
    paths:
      - path: /
        pathType: Prefix
  tls:
  - hosts:
    - k8s-dashboard.klopfi.net
    secretName: ingress-server-tls
