apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kured-discord-hook
  namespace: kured
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-sa
    kind: ClusterSecretStore
  target:
    name: kured-discord-hook
  data:
  - secretKey: hook
    remoteRef:
      key: kubernetes/kured-discord-hook
      property: hook
