apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kured
    repo: https://kubereboot.github.io/charts
    releaseName: kured
    namespace: kube-system
    version: 5.3.2
    valuesFile: values.yaml

