apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kured
    repo: https://kubereboot.github.io/charts
    releaseName: kured
    namespace: kured
    version: 5.4.5
    valuesFile: values.yaml

resources:
  - namespace_kured.yaml
  - sealedsecret_discord-hook.yaml