---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-discord-hook
  namespace: kured
spec:
  encryptedData:
    hook: AgBzFjhZ42rv3WJfke0Or4JPbehfUBurZkxC8TGEMrAtiDJuZAmuuJYauMuNMv3+MYMWVb/ZYdFQu/qGJkyBrNj5Li+PZlF5Ei0PCPWKgIWSTjwtl1IqcK3FwiBa951SyT+OTGezkFkrzQgxVytwFWlAl4FHN9Ae1DLASC3fCU6SP7t9X+pK/b5+Ke6YJmVRO60B6LMzHxqqCKXuFQz47a/UfO5fiUCDGe4HBVM9HZEVaVymixpzbYU3gqDJ7nLp7KcjvDch65ZlFYYi8b61E1GOYnAixaywYsZe6q1/gB/qI8HSy4B01pSp5EtVxUzqOrR6mqjVUJmu31+yHlYfZvBnD5CXk8I+xYQ16m+w5IPQDpfUa0UkLeVzuDlwMZiSh7I00Y0RTJF+Kn3DcJv8vWIOK9C1UO8vEr9OOON2mHCcp8uyAv16re3ysKcoVzE0qp7JDaLyFZvFv1sHkxL3v14l/iUJxSXlbIKiWAsv5F8B3OcAzh1C12BaP7ZpQXHVkJAH+vU4kqs6lo7+X77An9X4nxv8touH7arlaTlhuR3ddKsIQTCEL7OzzU3r+LCVCPh8dnFoY48z8TIkL2dXic0jCYcNfxDrSKolx31CiOmEAM8cFPdTSoN+ay5TRVO47E43XE3GHK8yNU+/HpxTCoiqmN9mSZZ16NQ6xKeZ68zLOc/k12mcGOJ4GytG+cw1gjC0S/S60vFrlsIdVn2pvJS2PDg2b/PzhEEXOGXbcDgu2SIiJGAYENAsH2Z4CGRDws1GNZlKIbwNCae1ouUSnCoe6Q1l/nhxyOcgEzKPJq8b3Y6O/y+kHzxbEA==
  template:
    metadata:
      creationTimestamp: null
      name: kured-discord-hook
      namespace: kured
