configuration:
  period: "30m"
  notifyUrl: "discord://${DISCORD_HOOK}"
  timeZone: "Europe/Zurich"
  annotateNodes: true

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoExecute"

extraEnvVars:
  - name: DISCORD_HOOK
    valueFrom:
      secretKeyRef:
        name: kured-discord-hook
        key: hook