apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions
rules:
- apiGroups:
    - networking.k8s.io
    - ''
  resources:
    - ingresses
    - services
  verbs:
    - get
    - list