apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions
subjects:
- kind: User
  name: sa-github-actions
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-actions
  apiGroup: rbac.authorization.k8s.io