apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions
subjects:
- kind: ServiceAccount
  name: sa-github-actions
  namespace: github-actions
roleRef:
  kind: ClusterRole
  name: github-actions
  apiGroup: rbac.authorization.k8s.io