apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions
  namespace: github-actions
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: github-actions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        deployment: github-actions
    spec:
      serviceAccountName: sa-github-actions
      containers:
      - name: github-actions-runner
        image: thisisnttheway/github-runner-image:latest
        securityContext:
           runAsUser: 1001
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
          - name: GITHUB_OWNER
            valueFrom:
              configMapKeyRef:
                name: github-actions-environments
                key: github-owner
          - name: $RUNNER_LABELS
            valueFrom:
              configMapKeyRef:
                name: github-actions-environments
                key: labels
          - name: GITHUB_PAT
            valueFrom:
              secretKeyRef:
                name: github-actions-pat
                key: github-pat