apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-octodns-data
  namespace: github-actions
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-sa
    kind: ClusterSecretStore
  target:
    name: actions-octodns-data
  data:
  - secretKey: rfcHost
    remoteRef:
      key: kubernetes/actions-octodns-data
      property: rfcHost
  - secretKey: token
    remoteRef:
      key: kubernetes/actions-octodns-data
      property: token
