apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-actions
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-sa
    kind: ClusterSecretStore
  target:
    name: controller-manager
  data:
  - secretKey: github_app_id
    remoteRef:
      key: kubernetes/controller-manager
      property: github_app_id
  - secretKey: github_app_installation_id
    remoteRef:
      key: kubernetes/controller-manager
      property: github_app_installation_id
  - secretKey: github_app_private_key
    remoteRef:
      key: kubernetes/controller-manager
      property: github_app_private_key
