apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-klopfi-bot-ssh-key
  namespace: github-actions
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-sa
    kind: ClusterSecretStore
  target:
    name: gh-klopfi-bot-ssh-key
  data:
  - secretKey: key
    remoteRef:
      key: kubernetes/gh-klopfi-bot-ssh-key
      property: key
