apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    releaseName: actions-runner-controller
    namespace: github-actions
    version: 0.9.3
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    releaseName: actions-runner-set
    namespace: github-actions
    version: 0.10.1
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - additional_rs-controller_perms.yaml
  - cr_github-actions.yaml
  - crb_github-actions.yaml
  - externalsecret_actions-octodns-data.yaml
  - externalsecret_controller-manager.yaml
  - externalsecret_gh-klopfi-bot-ssh-key.yaml
  - ns_github-actions.yaml
  - pvc_cache-storage.yaml
  - rb_github-actions-kube-mode.yaml
  - sa_github-actions.yaml