apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: actions-runner-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    releaseName: actions-runner-controller
    namespace: github-actions
    version: 0.23.7
    valuesFile: values.yaml

resources:
  - cr_github-actions.yaml
  - crb_github-actions.yaml
  - ns_github-actions.yaml
  - pvc_cache-storage.yaml
  - runnerdeployment_default.yaml
  - sa_github-actions.yaml
  - sealedsecret_actions-cloudflare-token.yaml
  - sealedsecret_controller-manager.yaml
  - sealedsecret_gh-klopfi-bot-ssh-key.yaml