apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cluster-runner
  namespace: github-actions
spec:
  template:
    spec:
      labels:
        - kubernetes
      organization: KlopfiNet
      resources:
        requests:
          cpu: 1500m
          memory: 2000Mi