apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cluster-runner
  namespace: github-actions
spec:
  template:
    spec:
      labels:
        - kubernetes
      organization: KlopfiNet
      env:
        # OctoDNS stuff
        - name: CLOUDFLARE_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-octodns-data
              key: token
        - name: RFC2316_HOST
          valueFrom:
            secretKeyRef:
              name: actions-octodns-data
              key: rfcHost
      resources:
        requests:
          cpu: 250m
          memory: 500Mi