apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cluster-runner
  namespace: github-actions
spec:
  template:
    spec:
      env:
        # OctoDNS stuff
        - name: CLOUDFLARE_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-octodns-data
              key: token
        - name: RFC2316_HOST
          valueFrom:
            secretKeyRef:
              name: actions-octodns-data
              key: rfcHost
      initContainers:
        - name: install-terraform
          image: hashicorp/terraform:latest
          command:
            - sh
            - -c
            - mkdir -p /tooling/.local/bin; cp /bin/terraform /tooling/.local/bin/terraform
            # The mkdir thing is a trick to inject binaries into $PATH of the runner
          volumeMounts:
          - name: tooling
            mountPath: /tooling
      labels:
        - kubernetes
      organization: KlopfiNet
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
      serviceAccountName: sa-github-actions
      volumes:
        - name: tooling
          emptyDir: {}
        - name: ca-bundles
          configMap:
            name: klopfi-net-ca
            defaultMode: 420
        - name: cache-volume
          persistentVolumeClaim:
            claimName: cache-storage
        - name: ssh-key
          secret:
            secretName: gh-klopfi-bot-ssh-key
            defaultMode: 384
      volumeMounts:
        - name: ca-bundles
          mountPath: /etc/ssl/certs/
        - name: tooling
          mountPath: /home/runner/.local
          subPath: .local
        - name: cache-volume
          mountPath: /cache
        - name: ssh-key
          mountPath: /var/gh-secret
          readOnly: true
