---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-klopfi-bot-ssh-key
  namespace: github-actions
spec:
  encryptedData:
    key: AgCFYL5JeIDPEwPi9TYjQtrrlenfOOJvLvEik0h3OVTAykdrh3v6zK9Dd9dUKkI9504NJEMfbYZvoNdjXdH3paezl9K80cPCt4ngYfQ4/wscSxpeXUjLNDe01Fvj/SAh07v+PIHQsIA7asiJ5P6kt7049Rj9/wyg8gTDylrvPxFlUtlz9JRVOPA+S51OxtyQ9lk/WdME7uC+xcKmt+FEI1lpylq8fQBPAS9LHjC/93+N42are0n+YVm43defmdpy6yyrXEx3QErIsqF4mq0mct77QrMwv8LD2wao+i+nvzds2d26hitpR3JJ0Q1XoIyCIzwdSf1IAKA87rrUXtwpdG0KwH+CF3pfrrqg28Y+epKGOfKij+4pkVM9ACt1WSCIigupgGJuPfvu4PD9knoaWMtSNDGK5BC+/3yHq3OzP9ty/qoVka06P+Fa+W2OIpYEzOnJa9F7+I3hEO7nCJoX6oHF6mT+Jx6xppygMOR1i6ShJdVLLeur+CbK+GSUvDoqyX4CSQpVQ/1RI1teRJR1NJo8S/gz4sqmwRCU8NHUZpWC811tniipkehMIQ35Ym9kwUy8ysvT7d53i7wdpzz/THxEGUR+v5gxURDaJ3l4zo8eHUAsEfonLYhBugac3arRXOvP7qFix9WO5WYWRk0DadNY6qE4ZU7xwRqGYqFZfu7zg8bz+XzSIiwAgYQXsYIN9WyM+qWJPRmp5PasWNbbK2p9DOl5ER17dxgfFUse6o8MKi4G/Ik5aAK13SWtlMEA+wmnzikYa1uddJjfpzziEqnsgyq0ggY2L3BwWW+3i3YIZesfF22bmF0g9Yu3N5UIq7ZFYHWZ24cAqZPO+18kACP4zIFILz2Fatr5l0IuJtaFbCB3wrt7ZGxbLBRxzBYsRcmOKsdKVwKpU1NLVT8FnM7e0o7z0YwrRg6X2PZ2uIbchszi4wT67FMb4PT9czAM9ljEeo+wPK0boP6Cj50bBRm06te4/tip44rB/EBmjUYiTIrYStomutgoJeJtRp5L/AianKM79nuynYNVh3LXklt1lMMIkaer6+5CS0s9qRIap+FsPqZsQWgpultD2tcxKms4Ni/4Gs8f/BO++IwpIBKACE52fn4GoD5RZZQtx7KNh2v8kEnEQGXpY7ykLsVx9At0CUS/rsK2vtP0ifqXUTrEoNPnyBJ5RcPAV9l3NnKz4CQhHcnSc0/c9QJbWZMoEekS2JE=
  template:
    metadata:
      creationTimestamp: null
      name: gh-klopfi-bot-ssh-key
      namespace: github-actions
