apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.apps.klopfi.net"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: "external-secrets"
          name: "vault-token"
          key: "token"