apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    releaseName: external-secrets
    namespace: external-secrets
    version: 0.9.16
    valuesFile: values.yaml

resources:
  - clustersecretstore_vault.yaml
  - ns_external-secrets.yaml
  - sealedsecret_vault-token.yaml