apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets 
    namespace: sealed-secrets
    version: v1.13.2
    valuesFile: values.yaml

resources:
  - namespace_sealedsecrets.yaml