apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com
    releaseName: paperless-ngx
    namespace: paperless-ngx
    version: 0.19.0
    valuesFile: values.yaml

resources:
  - ns_paperless-ngx.yaml
  - ing_paperless-ngx.yaml