env:
  TZ: Europe/Zurich
  PAPERLESS_URL: https://paperless.apps.klopfi.net

persistence:
  data:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/data
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/media
    accessMode: ReadWriteOnce
    size: 8Gi
  consume:
    accessMode: ReadWriteOnce
    size: 4Gi
  export:
    accessMode: ReadWriteOnce
    size: 1Gi