server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault.apps.klopfi.net
    tls:
      - secretName: wildcard-klopfi-net
        hosts:
          - vault.apps.klopfi.net
  nodeSelector:
    infra: "true"
  tolerations:
    - key: "node-role.kubernetes.io/infra"
      operator: "Exists"
      effect: "NoSchedule"

serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true