apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    releaseName: velero
    namespace: velero
    version: 5.1.6
    valuesFile: values.yaml

resources:
  - namespace_velero.yaml
  - sealedsecret_cloud-credentials.yaml