apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    releaseName: velero
    namespace: velero
    version: 5.1.6
    valuesFile: values.yaml

  # The vmware-tanzu chart does not install the CRDs...
  - name: velero-crds
    repo: https://wiremind.github.io/wiremind-helm-charts
    releaseName: velero-crds
    namespace: velero
    version: 5.1.4

resources:
  - namespace_velero.yaml
  - sealedsecret_cloud-credentials.yaml