apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: sealed-secrets-keys
  namespace: velero
spec:
  # Default sealed-secrets key rotation is every 30 days
  schedule: 0 0 1 * *
  template:
    includedNamespaces:
    - kube-system
    includedResources:
    - secrets
    labelSelector:
      matchLabels:
        sealedsecrets.bitnami.com/sealed-secrets-key: active
    ttl: 1440h0m0s