---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAeX1F3IDGRNKoC/kihWyvRlc1kEagTbu9rbO4jh3ETtBazA6jxuWQAwWOduTh9udzY9KB3UsPzOnZ22xCrX+KuwQVKVyt6KKpMfezAaLC8aQNF6mBtmbvqlulWrWt11mk2ABS6on0EtX1DaLShtOLk03fR3k7Db1+g0YLBF1GOR/Zc1O0k4HmD6UZGotQEYUIK75VPneNM6NnQFPcWzsh8Bw6CLMOw2wqHp3wd4o4EI+X48pYg/jepmryG1lhR/7ARyZjcOyGJ4O/KtaYhTzQw22qagekfP3YfkoFdyT8E+hf/JYRatwQIXhy0sPiTSLb5zf+V6pNfAtRyF6auoccJ+kdGIvDyTv+XTSg2FjjcH5si5XbNalonrm7bxsbCiLcfqmzNjSdeRQoaTW4pcV0MXzejQWGC9lo7MAxBhuKMPs727rOktXz47gUIpQ1sgZbfgY3h4AXKZAF7DHthwQDa3l7EpzHvkevJUaUZUidtF0tsqDZdORRwXAe1V+GZRQbwMIJa+jc/IDGi/mba3xKAUna9AXm/KwByE7IQWl/6g/uo/3zdKlJxs/j1AQnjFDnimEemTppDzPr8IcfkuTa6+5Z5zLh4nM+iVZv9mLCoG5B99vwo3wddl1u6KCN8aPS9gvf/j/aSQJ8fz+OakvhFgxqK1qoT60skp9KDq3zGfdDCldKChrxMZf8nxR/SxXQF+vB9/7x7eh6snM9GCzvVbDH/xKPOQMRbfrtxA6Q3MJDfj2jcehKjOcu6pHrQtgDVclMkHIui6Sm5O2F/3hCZwtYVhW8EgaghaYIMGOVEOZD2a08llkXhevetNzMzP3QFEGkGMZ+ne7n9DrBTSnJ2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
