---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA1KZrvHGaqdA+VP8ZRz14UjLa5mbBRHUzGrZRLVszUefTIOE5O2WFyBu8iuWZ3rzhkr5PyJTCjstHIFiOfDLVxhh9XxA8Y5zfn4BoK0WmXM6V23vs5pJAtWofcpV1AfLW0wnDNd+hMFQ8vtkYWg6wknYgldkYy9VR7HUynL73DV67Qjx0M/96w0V+peXDlYirV2mPkvwbG8MXiDQXyU/5dpskeEvYNNGzLGB7anpKrTF39XMPJrQJ4lm3H9+/FitSBLuAjSlERjHkXGyYr6A7XBD8IysSVhZW6kEAmYKkxh0dVeIpOeYddTrC4xmKPXj+6wvz1sgOQcVPQWlhgsaCLerRDCYrTaKXWeARMMplAq2sGyBa5U2Ap5BqgExSutzPRgE83UaU2wyGuU0h8QNzXcxIiTMn1y2izQ3II7EnaHDIR3zPVJJUkDzwQXAxgf92PXJkol0ky+n8QnHEzA5sUvl7a00PN5qiny7eVz/OeePD7vQofxiOV1/y/bYqCrvLSJ7Y+QzI/06bkCjCseg1lGGYJ4A08CT8UMxn11uiu/czfcVD4jF9ppd6RZyMEzlKLt3e8/vypvPIp7PUF8UHjUXzFCrBi4CC8vWBq5P8gkSg9BF5D5nAccwct+Cxj4sUASrQPsUHL0X0/5v086DyR5RRZN4dO0RyXJexAhjT8j5MD5Pcrkob2s+zhJZxq4MYJY11TApntbu+tbyKCL2iJYppYYir7kkXcG2Oye8FtILpPLmRKcXftZ1KEjOad4DBSNZqtwqG+ojO5ZbtmF2f7v9O7vPd5AvStH5AXyoBJ8vcq2nS+LRGwSNUqlF9RgR4KxHr12GDnVMtFdBrKXWy0
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
