---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBLzcQQY72SYx93OPSmfKvQwWN0c7OeWgQNLEiy1CGTloDn46N3xOwyH3fkRC9v3LhqoII05KKh2bOv6/vyOq13LLRbhR44hqpgozXyAZfLbSmSTX/MKfJ2KKZwhfEfdD3jn32BlvsP0AsAPADzklkXfXcf54ptNmlVCy/PtbYOoZkf9uX84Yp6bUU/5c07E0f+jjKhfmwF4V6bwjVmm0JXg/swSpDrOg657xevgiB8C5N6IGTyjWwaucEXO/dbuVqL86W5f+4etasEAvETc+hU5EtAVRfixjAl4AinS0P+k7DCBcU+CKMdDsPK+X8OF7FFcMiuTrXV9t9AOow7IbGDty0N3q3IZ0Y4P64d5SnOlyYvECWROK+Lxr8qiNGgNoeuZ/9AqjEaVNn5lr3+Pi3ZN+41CB1TjKNoGYPtZ0DYpBZMf0+gnXRsjnqM1RS0cZJtDVQfZs1nhgyfzr/ozVJ7Y7pRorTgS2mS+dSV65v8zTJKSBgRYJyfV10k36z+OzkPbHLL2uFaIq1R9fstPIxp9rEg0l5QQzcmeJOQJxjDjui7dX2zANIUbq1FmvVxde5wmVFYjnW7MQim+nShs9/gktqu7UBY0QBdbnn8AbduCjYF2gYLH08ZwDHgJA8eIjWqSCg3q7JNhfkKFNoRsGwYK6/lI4Vvnbqh5l9b7KV2YlCX5Lw0+/tZpDNmgz+qebSRLgzrKwfk9+J52YLcOzVlzVl04XXe/14U+7O67G9/pAcccnLKpoNJ/slZUXS0wAbjUvx+/UkgnQ1rTaTGRtOvy3eBpA==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
