---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBN0M7E2VAnMipx/btHcQl+BZJc9wBK1YkpWYgmpZcLnjGuO0cr+4K8G+a6z4RJrtOj3O89Ttoqn7UqK/g+Nc98bEPo0QY7YCPQXj0Q0UwMM0ATtLa9yS5ICDYpTpefCdl0hCVU2gi+uSpmF/kNrFbQj80qfED7ViwgtA4QZlgcm2AVO6eyT5614c4RjgYRJBFri0uqExeczav+cFe4D8TCo4HTJDXm5wkpTXkOAc/dZckg1XwOHUdZhsvT+X42w5ad7TLy4QC4iyU58/PhaPc9+1Zn+Juu9M04/WEDbOS9eR/4rc4PO7jCkIaPKIup1HchEGnPNaUjs/ioJwctyQUU9SMQJF6TlegloA3fyHtIQVFZ5ZC/MIg/Gz22iiXbhgu5YIBkvBDMrw985qyVIEYZE+8vMPe+3snjlNBWl6cRiHKbhfBqoAPssJMZ/EAGAYOLyPILM7b0unpJ+k40g5waGpiKlwaJVDwNMQxwIsmjDKICzszKxDHbl5bk0toJ6VD/PRF4bNXDZYfUFVRriiJPKsMvrQj8NwBUuOVy6yS3xsnK2Yn1l/pHSWb9ChIxgOWT0g3X3lExFgfAiyGTe/VYOFYIl6s/Qb9q8oswAiQL4WoBjiAmFh1gm3Kxcs2Y9jFnrxrO8MV75LCT9UDzE7+KtrsqoMlt7LzNr5nU1ODXYWAmbvlqAfBGsvsc09EnjCCpx9zJ1hclZpZ6MEmd+kTTQ8HXDuwKjdiNjBRb8FEgPvjoG4ma3SxpFH54KmZDhyOt8LjytE5lWoc0ydr5h47k/RrKwFP7Nxqi8NZ/E0nhYeCeDiWBoqgan9rSPmCdBXljf8HeWT575S6C6pqXyKBw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
