---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCILKYDpFCitAs0N2N+aQkN/c5QNMnUsH2iyt8sgMvHXnuO5jDGr6Xz15XQaBn1jMLX+1RJtXicFvAg/RWpKBofTShZAnZZjkbsOtbqIBubeiTA58gBhAKGJCPr1Z+8xfKH6H1WqjyiyXCxWDVRXSJAsEbe1/haqbf0ee5g5zkCNdnSaL1HDj2MQckzuGF6BwpzHcPOp2Re1zB6RshU8JBXADep04xMSRXpyLLOoRQcMSKyBZ7XAs3B1I2yoVZsKkCF6XnApAO1yoWkPFBS7vJ+kSNT5G7Kt0yYYQYxRSwXMgJ9EELGFiYrJ0Jxo9ILqk7+xvHmfWsUvDMNj15QUWfvZEN76G4cfqQsgxgTrv53FMp8ytB4L++/htxcE4S22kFxeF9itwySGaem2P2BE4Ridrrh7Re1Uq6UBwjs1Pf9v/4lAAyYmDewb0/V3iiFPGyVldbMj/MFUH8OzC6I/lTDJFCeSloX3V2AHXS8PszzUU0KetSv8O3jPwg97P3rB6h95nyF0572tj5+GB1hp/okhdtwqjwqP6XiGt3wW4eUHQqtPzjQzzMctOsyizofVEvSfsbj1ages3VU0ex93OjzeJ1ujdMgvfuCe9vd0QJEAXfEuhAKr/AK5BMyfLf373FT3/z2X3MDqlcFT896IRfexZzbOGqKUTEU1i8RwRiWiUQNrn1fBmijPyumBOMFNz4hM/FYb1EHrKm4s1oqyLk75D+jqp7edVsl/O52M+3BCFQPKVsrcHmigZuTJm3U8JCRzNqAIU6UES01JcqHAwAUzN2GOBVGXAvhqTr6wKGujBIEbl1+BJPcXgQ2GgmBKtJpGb5TvDwusyiwM+/aw40FPQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
