---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA+aKka9O/NB5uNJNZRjPAU/ryE/T3xOiGlyRzAgb5QcCJQWtdTwSa33g+KcR5XJV4xedC2ukWyzgqh1a5P5eLcRnQ9fxxKuegnO/gilbQXFm1Fsm2YbF0i5WH4YmYQHyi2Acrf/nL4/p0csnICuwSDVqVcc5D7LLluK7SpQ9UjEnaWwZTP7J23InNPUzL//o/SyNf3ktW63jE5YB1C8mbOuDUIIx+SICVhrLQMXZTN+/+Ebso6ojcrcEn3vwGx4yfWI2iNP92spglyWutvxPjFOEr1M6OdaYSGWmH8ecL2cjY/BoYLniMO50KRwOMhtxjvrij2K9N7N9v08TnrRJWww2RcvXpOWHOTqBjUyf9wgwChKu3tIWysizOaegAd7ontS95BYU8GPVJsqPsbMjDogD2OhxQQ0wCO/l65vQHsOBwBA/woZopzVf+Z0JdlUOj4pN/0lUULQfl1kDOjHcA6kpM4oryxUwqhugxZPV4R/VBF7EHHBljLbDzctIeGehW+ILjyi5RiKX7MhGNXd5j2MS6oQvgQt3+a4AiWQHCYbtDtr0+zohiG2xriyzdbWhT5KD3t9gOWvDVBc/Thytywl7ARhF4eeBjhZdoZ/IFWhs9vKgPJKx/Zl+FOanLQNYiF32Q/HAdY5EcT9qUZE8FuAT+JPh78BkYRzhOSmZsd2l87CSxoBmd4qp2a4nSt0PuM2UN8xUTrsgxj0L55Etp9anfrL0Bvgx7P6in0UKGITd7Qoq8S/g2PnWI5911NcAEQP8TAXm3OpPZlnnQ0lPXcDmJwV+KpNTsBvZ8jMN0Vy3Tmm+S7FKsNtFZITv5NsOZ820smmIjlaN/MA/gOOPrWRw==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
