configuration:
  uploaderType: kopia
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: velero
    default: true
    accessMode: ReadWrite
    credentials:
      name: cloud-credentials
      key: cloud
    config: 
      region: minio
      s3ForcePathStyle: "true"
      s3Url: https://minio.klopfi.net:9000
      profile: "default"
      insecureSkipTLSVerify: true
  volumeSnapshotLocation:
  - name: default
    provider: aws
    bucket: velero
    default: true
    accessMode: ReadWrite
    credentials:
      name: cloud-credentials
      key: cloud
    config: 
      region: minio
      s3ForcePathStyle: "true"
      s3Url: https://minio.klopfi.net:9000
      profile: "default"
      insecureSkipTLSVerify: true
  features: EnableCSI

credentials:
  existingSecret: cloud-credentials

deployNodeAgent: true

# Not adding this will actually troll you
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

upgradeCRDs: false